# Generated by Django 4.1.7 on 2023-05-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='durType',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('Available', 'Available')], max_length=200, null=True),
        ),
    ]
