# Generated by Django 4.1.7 on 2023-05-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_order_durtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='durType',
            field=models.CharField(choices=[('Long term', 'Long term'), ('Short term', 'Short term')], max_length=200, null=True),
        ),
    ]
